language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- pypy
- pypy3
env:
- PYMONGO=2.7
- PYMONGO=2.8
- PYMONGO=3.0
- PYMONGO=dev
matrix:
  fast_finish: true
before_install:
# Install MongoDB
- travis_retry sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
- echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' |
  sudo tee /etc/apt/sources.list.d/mongodb.list
- travis_retry sudo apt-get update
- travis_retry sudo apt-get install mongodb-org-server
install:
# 1. Install Python
- sudo apt-get install python-dev python3-dev
# 2. Install general requirements (Python packages)
- pip install -r requirements.txt
# 3. Enums in Python only became available in 3.4.
#    The package `enum34` listed in `requirements-python<3.4.txt` is a backport.
- if [[ $TRAVIS_PYTHON_VERSION == 2* ]];     then pip install -r 'requirements-python<3.4.txt'; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.2* ]];   then pip install -r 'requirements-python<3.4.txt'; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.3* ]];   then pip install -r 'requirements-python<3.4.txt'; fi
- if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then pip install -r 'requirements-python<3.4.txt'; fi
# Coverage 4.0 doesn't support Python 3.2. Install an older version
# before coveralls tries to install the latest. (pypy3 is really Python 3.2)
- if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]];   then travis_retry pip install 'coverage<4.0'; fi
- if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then travis_retry pip install 'coverage<4.0'; fi
- travis_retry pip install tox>=1.9 coveralls
#- travis_retry tox -e $(echo py$TRAVIS_PYTHON_VERSION-mg$PYMONGO | tr -d . | sed -e 's/pypypy/pypy/') -- -e test
script:
#- tox -e $(echo py$TRAVIS_PYTHON_VERSION-mg$PYMONGO | tr -d . | sed -e 's/pypypy/pypy/') -- --with-coverage
# Run tests with coverage (similar to `python -m unittest2`
# or `unit2` on Python 2.6.
- coverage run -m unittest2
after_script:
# Submit coverage to coverall.io
- coveralls --verbose
